events {
    worker_connections 1024;
}

http {
    upstream finance_backend {
        server 127.0.0.1:19002;
    }

    server {
        listen 9002 ssl;
        server_name ztna-finance localhost;

        ssl_certificate /certs/finance-service.crt;
        ssl_certificate_key /certs/finance-service.key;
        ssl_client_certificate /certs/ca.crt;
        ssl_verify_client on;
        ssl_verify_depth 2;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://finance_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-SSL-Client-Cert $ssl_client_cert;
            proxy_set_header X-SSL-Client-Verify $ssl_client_verify;
        }
    }
}
